"""Create Doc model

Revision ID: 5b67562fa3ac
Revises: 
Create Date: 2022-08-26 08:40:06.862550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b67562fa3ac'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=100), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('thumbnail', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='docs'
    )
    op.create_index(op.f('ix_docs_docs_name'), 'docs', ['name'], unique=False, schema='docs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_docs_docs_name'), table_name='docs', schema='docs')
    op.drop_table('docs', schema='docs')
    # ### end Alembic commands ###
